#!/bin/bash

git submodule update --remote Groupr-Frontend

cd Groupr-Frontend || exit
if hash yarn 
then
  yarn
elif hash npm
then
  npm i
else 
  echo need yarn or npm to install node packages
  exit 1
fi

node_modules/.bin/webpack --config dev.webpack.config.js --color --progress
mv bundle.js ../Public
cp assets/html/index.html ../Public
cd ..

